apiVersion: v1
kind: Pod
spec:
  containers:
  - name: shell
    image: ubuntu
    command:
    - sleep
    args:
    - infinity
  - name: kaniko
    image : gcr.io/kaniko-project/executor:v1.8.0-debug
    command:
    - sleep
    args:
    - infinity